<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Michaela rieser" />

<meta name="date" content="2021-10-04" />

<title>Exam 1</title>

<script src="site_libs/header-attrs-2.5/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Michaela's Site</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Assignments.html">Assignments</a>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Exam 1</h1>
<h4 class="author">Michaela rieser</h4>
<h4 class="date">10/04/2021</h4>

</div>


<p>This page will contain all the assignments you submit for the class.</p>
<div id="instructions-for-all-assignments" class="section level3">
<h3>Instructions for all assignments</h3>
<ol style="list-style-type: decimal">
<li><p>Download the Assignment1.Rmd file from Canvas. You can use this as a template for writing your answers. It’s the same as what you can see on my website in the Assignments tab. Once we’re done with this I’ll edit the text on the website to include the solutions.</p></li>
<li><p>On RStudio, open a new R script in RStudio (File &gt; New File &gt; R Script). This is where you can test out your R code. You’ll write your R commands and draw plots here.</p></li>
<li><p>Once you have finalized your code, copy and paste your results into this template (Assignment 1.Rmd). For example, if you produced a plot as the solution to one of the problems, you can copy and paste the R code in R markdown by using the <code>``{r} ```</code> command. Answer the questions in full sentences and Save.</p></li>
<li><p>Produce a PDF file with your answers. To do this, knit to PDF (use Knit button at the top of RStudio), locate the PDF file in your docs folder (it’s in the same folder as the Rproj), and submit that on on Canvas in Assignment 1.</p></li>
<li><p>Build Website, go to GitHub desktop, commit and push. Now your solutions should be on your website as well.</p></li>
</ol>
</div>
<div id="assignment-1" class="section level1">
<h1>Assignment 1</h1>
<p><strong>Collaborators: Sara Whitelaw </strong></p>
<p>This assignment is due on Canvas on Monday 9/20 before class, at 10:15 am. Include the name of anyone with whom you collaborated at the top of the assignment.</p>
<div id="problem-1" class="section level3">
<h3>Problem 1</h3>
<p>Install the datasets package on the console below using <code>install.packages("datasets")</code>. Now load the library.</p>
<pre class="r"><code>library(datasets)
#This command loads the data set. </code></pre>
<p>Load the USArrests dataset and rename it <code>dat</code>. Note that this dataset comes with R, in the package datasets, so there’s no need to load data from your computer. Why is it useful to rename the dataset?</p>
<pre class="r"><code>dat&lt;-USArrests
#This command renames our data set &quot;USArrests&quot; as dat. Renaming USArrests as dat makes the name shorter and easier to use. </code></pre>
</div>
<div id="problem-2" class="section level3">
<h3>Problem 2</h3>
<p>Use this command to make the state names into a new variable called State.</p>
<pre class="r"><code>dat$state &lt;- tolower(rownames(USArrests))
#This command renames the state names into a variable called state. </code></pre>
<p>This dataset has the state names as row names, so we just want to make them into a new variable. We also make them all lower case, because that will help us draw a map later - the map function requires the states to be lower case.</p>
<p>List the variables contained in the dataset <code>USArrests</code>.</p>
<pre class="r"><code>names(dat)</code></pre>
<pre><code>## [1] &quot;Murder&quot;   &quot;Assault&quot;  &quot;UrbanPop&quot; &quot;Rape&quot;     &quot;state&quot;</code></pre>
<p>This command is telling me what the different variables in the USArrests data set are.</p>
</div>
<div id="problem-3" class="section level3">
<h3>Problem 3</h3>
<p>What type of variable (from the DVB chapter) is <code>Murder</code>?</p>
<p>Answer: ‘Murder’ is a quantitative variable.</p>
<p>What R Type of variable is it?</p>
<p>Answer:In R, ‘Murder’ is a numerical variable, which means it is a quantitative variable that is expressed with decimal points.</p>
</div>
<div id="problem-4" class="section level3">
<h3>Problem 4</h3>
<p>What information is contained in this dataset, in general? What do the numbers mean?</p>
<p>Answer: This data set contains information about different arrest rates in the United States. It contains statistics for the arrests in every state for three crimes: rape, assault, and murder. The numbers are the amount of arrests per crime per 100,000 residents in that state. The urban pop variable is the percent of residents living in an urban setting.</p>
</div>
<div id="problem-5" class="section level3">
<h3>Problem 5</h3>
<p>Draw a histogram of <code>Murder</code> with proper labels and title.</p>
<pre class="r"><code>hist(dat$Murder, main=&#39;Murder Arrests per 100,000 residents&#39;, xlab=&quot;Number of Arrests&quot;, ylab=&quot;Frequency&quot;, xlim=c(0,20), ylim=c(0,20),col=&quot;pink&quot;,breaks=10)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-5-1.png" width="672" /> ### Problem 6</p>
<p>Please summarize <code>Murder</code> quantitatively. What are its mean and median? What is the difference between mean and median? What is a quartile, and why do you think R gives you the 1st Qu. and 3rd Qu.?</p>
<pre class="r"><code>summary(dat)</code></pre>
<pre><code>##      Murder          Assault         UrbanPop          Rape      
##  Min.   : 0.800   Min.   : 45.0   Min.   :32.00   Min.   : 7.30  
##  1st Qu.: 4.075   1st Qu.:109.0   1st Qu.:54.50   1st Qu.:15.07  
##  Median : 7.250   Median :159.0   Median :66.00   Median :20.10  
##  Mean   : 7.788   Mean   :170.8   Mean   :65.54   Mean   :21.23  
##  3rd Qu.:11.250   3rd Qu.:249.0   3rd Qu.:77.75   3rd Qu.:26.18  
##  Max.   :17.400   Max.   :337.0   Max.   :91.00   Max.   :46.00  
##     state          
##  Length:50         
##  Class :character  
##  Mode  :character  
##                    
##                    
## </code></pre>
<p>The average number of murder arrests per 100,000 residents is 7.788. The median for this data set is 7.250. Mean is the average value of a data set. Mean is equal to the sum of values divided by the number of values. Mean = sum of values/number of values. The Median is the middle value of a number set after all of the values have been put in an ordered list. Quartiles are three values that divide the data distribution into even fourths. In particular, Q1 and Q3 are important because we can use these two values to calculate the IQR, or interquartile range. The middle half of the data lies within the IQR.</p>
</div>
<div id="problem-7" class="section level3">
<h3>Problem 7</h3>
<p>Repeat the same steps you followed for <code>Murder</code>, for the variables <code>Assault</code> and <code>Rape</code>. Now plot all three histograms together. You can do this by using the command <code>par(mfrow=c(3,1))</code> and then plotting each of the three.</p>
<pre class="r"><code>hist(dat$Assault, main=&#39;Assault Arrests per 100,000 residents&#39;, xlab=&quot;Number of Arrests&quot;, ylab=&quot;Frequency&quot;, col=&quot;yellow&quot;, xlim=c(0,400), ylim=c(0,20),)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-7-1.png" width="480" /></p>
<pre class="r"><code>#The average number of assault arrests per 100,000 residents is 170.8.  The median for this data set is 159.0.  </code></pre>
<pre class="r"><code>#Histogram of Rape Arrests per 100,000 Residents 
hist(dat$Rape, main=&#39;Rape Arrests per 100,000 residents&#39;, xlab=&quot;Number of Arrests&quot;, ylab=&quot;Frequency&quot;, col=&quot;sky blue&quot;, xlim=c(0,60), ylim=c(0,20))</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-8-1.png" width="480" /></p>
<pre class="r"><code>#The average number of rape arrests per 100,000 residents is 21.23 and the median for this data set is 20.10.  </code></pre>
<pre class="r"><code>par(mfrow=c(3,1))
hist(dat$Rape, main=&#39;Rape Arrests per 100,000 residents&#39;, xlab=&quot;Number of Arrests&quot;, ylab=&quot;Frequency&quot;, col=&quot;sky blue&quot;, xlim=c(0,60), ylim=c(0,20))
hist(dat$Assault, main=&#39;Assault Arrests per 100,000 residents&#39;, xlab=&quot;Number of Arrests&quot;, ylab=&quot;Frequency&quot;, col=&quot;yellow&quot;, xlim=c(0,400), ylim=c(0,20),)
hist(dat$Murder, main=&#39;Murder Arrests per 100,000 residents&#39;, xlab=&quot;Number of Arrests&quot;, ylab=&quot;Frequency&quot;, xlim=c(0,20), ylim=c(0,20),col=&quot;pink&quot;,breaks=10)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-9-1.png" width="480" /></p>
<p>What does the command par do, in your own words (you can look this up by asking R <code>?par</code>)?</p>
<p>Answer:The command par is used to to set graphical parameters. In this case, it can be used to put multiple graphs on a single plot.</p>
<p>What can you learn from plotting the histograms together?</p>
<p>Answer: From plotting the histograms together, I can compare frequency of the arrest rates for these three crimes. I can see that the number of assault arrests per 100,000 residents has a much wider spread than rape arrests and murder arrests. The number of murder and rape arrests per 100,000 residents has a much smaller spread. This shows that on average, there are more assault arrests per 100,000 residents in the United States than murder or rape arrests. Looking at histograms graphed together, we can visually compare how different, or similar, the statistical characteristics, such as mean, median, spread, of the different data sets are.</p>
</div>
<div id="problem-8" class="section level3">
<h3>Problem 8</h3>
<p>In the console below (not in text), type <code>install.packages("maps")</code> and press Enter, and then type <code>install.packages("ggplot2")</code> and press Enter. This will install the packages so you can load the libraries.</p>
<pre class="r"><code>#install.packages(&quot;ggplot2&quot;)
#install.packages(&quot;maps&quot;)
#&#39;maps&#39; and &#39;ggplot2&#39; were already downloaded, so I was getting an error message when I had the code in for it.</code></pre>
<p>Run this code:</p>
<pre class="r"><code>library(maps) 
library(ggplot2) 

ggplot(dat, aes(map_id=state, fill=Murder)) + 
  geom_map(map=map_data(&quot;state&quot;)) + 
  expand_limits(x=map_data(&quot;state&quot;)$long, y=map_data(&quot;state&quot;)$lat)</code></pre>
<p>What does this code do? Explain what each line is doing.</p>
<p>Answer: The library code loads the desired packages. In this case, it is loading the packages called ‘map’ and ‘ggplot2’. The combination of the ‘map’ package and the ‘ggplot2’ package allows for the display of maps. The next line is giving the code for the map that we want to generate of the United States. The quoting function aes is for aesthetic mappings and the code that follows is describing what is making up the aesthetic mapping. We are pulling data from the USArrests data set, which was shortened to dat. The fill=murder command is telling R that we want the states to be shaded in according to the“Murder” data set. The expand_limits code describes the x and y axis by longitude and latitude.</p>
</div>
</div>
<div id="assignment-2" class="section level1">
<h1>Assignment 2</h1>
</div>
<div id="title-assignment-2" class="section level1">
<h1>Title: Assignment 2</h1>
<p>Subtitle: Crim 250: Statistics for the Social Sciences Name: Michaela Rieser Date: 09/23/2021</p>
<p>Problem 1: Load data</p>
<p>Read the data</p>
<pre class="r"><code>read.csv(file=&quot;dat.nsduh.small.csv&quot;)</code></pre>
<pre><code>##     mjage cigever alcever AGE2 sexatract speakengl irsex
## 1      21       1       1   15         1         1     1
## 2      20       1       1   14         1         1     1
## 3      14       1       1   16         1         1     1
## 4      17       2       1    8         1         1     2
## 5      11       1       1   13         2         1     2
## 6      18       1       2   14         1         1     1
## 7      12       1       1   15         2         1     2
## 8      16       1       1   14         1         1     1
## 9      14       1       1   16         4         1     1
## 10     15       1       1   11         5         1     1
## 11     28       1       1   14         1         1     2
## 12     12       1       1   15         4         1     2
## 13     13       1       1   13         1         1     1
## 14     20       1       1   14         1         1     1
## 15     33       1       1   14         1         1     2
## 16     20       1       1   16         1         1     1
## 17     26       1       1   13         1         1     1
## 18     18       2       1   13         1         1     2
## 19     18       1       1   17         1         1     2
## 20     36       1       1   15         2         1     2
## 21     15       1       1   15         1         1     1
## 22     17       1       1   13         5         1     1
## 23     14       1       1   15         1         1     2
## 24     13       1       1   16         1         1     1
## 25     14       2       1    5        99         1     2
## 26     15       1       1   15         1         1     2
## 27     17       2       1    6        99         1     1
## 28     18       1       1   15         1         1     1
## 29     18       2       1    9         1         1     2
## 30     16       1       1   14         1         1     1
## 31     19       1       1   15         2         1     1
## 32     17       1       1    7        98        98     1
## 33     19       2       1   15         1         1     2
## 34     17       1       1   15         1         1     2
## 35     16       2       1    6        99         1     2
## 36     21       1       1   17         1         1     1
## 37     20       2       1   11         1         1     1
## 38     12       1       1   15         1         1     2
## 39      8       1       1    6        99         1     1
## 40     14       1       1   15         1         1     2
## 41     18       1       1   15         1         1     2
## 42     16       1       1    9         1         1     1
## 43     18       1       1   15         1         1     1
## 44     16       1       1   13        97        97     2
## 45     19       2       1   15         1         1     2
## 46     18       1       1   13         1         1     2
## 47     16       2       1    5        99         1     1
## 48     14       2       1   12        97         2     2
## 49     34       2       1   15         1         1     2
## 50     14       1       1   12         1         1     1
## 51     16       1       1   14         1         1     2
## 52     18       1       1   12         1         1     1
## 53     18       1       1   12         1         1     1
## 54     18       2       1   12         1         1     2
## 55     20       1       1   15         1         1     1
## 56     15       1       1   16         5         1     1
## 57     24       2       1   15         1         1     1
## 58     16       1       1    8         1         1     2
## 59     14       1       1   15         3         1     2
## 60     16       1       1   15         1         1     1
## 61     15       1       1   16         1         1     1
## 62     17       2       1    7         1         1     1
## 63     12       1       1   11         5         1     2
## 64     16       1       1   11         1         1     1
## 65     11       2       2    1        99         1     2
## 66     16       1       1   15         2         1     2
## 67     18       2       1    7         1         1     2
## 68     16       2       1   12         1         1     2
## 69     14       1       1   13         2         1     2
## 70     16       2       1   15         2         1     2
## 71     11       2       1    1        99         1     1
## 72     19       1       1   15         1         1     2
## 73     16       1       1   14         1         1     1
## 74     20       1       1   15         1         1     1
## 75     10       1       1   14         1         1     1
## 76     16       1       1   15         1         2     1
## 77     23       1       1   13         2         2     2
## 78     22       1       1   15         1         1     2
## 79     12       2       1   11         1         1     1
## 80     17       1       1   15         1         1     2
## 81     22       1       1   11         1         1     1
## 82      9       1       1    4        99         1     1
## 83     18       2       1   12         3         1     1
## 84     12       1       1   16         1         1     1
## 85     23       2       1   17         2         1     2
## 86     15       1       1   16         1         2     1
## 87     17       2       1   16         1         1     1
## 88     20       1       1   13         1         3     2
## 89     16       1       1   15         1         1     1
## 90     23       1       1   15         1         1     2
## 91     18       2       1    9         3         1     2
## 92     17       2       1    6        99         1     1
## 93     16       1       1   13         1         1     1
## 94     12       1       1    6        99         1     2
## 95     18       1       1    8         1         1     2
## 96     16       2       1    7         1         1     2
## 97     15       1       1   15         1         1     1
## 98     14       2       1   12         1         2     1
## 99     15       1       1   15         1         1     1
## 100    16       1       1   12         1         1     2
## 101    20       2       1    9         1         1     2
## 102    18       1       1   15         2         1     2
## 103    15       2       1    6        99         1     1
## 104    20       2       1   11         1         1     2
## 105    13       1       1    6        99         1     1
## 106    19       2       1   15         1         1     2
## 107    20       1       1   15         1         3     2
## 108    18       1       1   15         1         1     2
## 109    16       1       1   14         1         1     2
## 110    18       1       1   15         1         1     2
## 111    15       1       1   17         2         1     1
## 112    10       1       1   17         1         1     1
## 113    15       2       1   16         1         1     1
## 114    20       2       1   10         1         1     2
## 115    18       1       1   10         1         1     2
## 116    14       1       1    9         1         1     2
## 117    21       2       1   11         1         1     1
## 118    18       1       1   14         1         1     1
## 119    18       1       2    8         3         2     2
## 120    22       2       1   16         1         1     2
## 121    15       1       1   10         1         1     1
## 122    16       1       1   11         1         1     1
## 123    22       1       1   13         1         1     1
## 124    15       1       1   15         1         2     2
## 125    16       1       1   14         1         1     1
## 126    16       2       1    7         1         1     1
## 127    17       1       1   13         1         1     1
## 128    16       1       1   13         2         1     2
## 129    19       1       1   14         1         1     1
## 130    27       1       1   15         1         1     1
## 131    22       1       1   15         1         1     1
## 132    17       2       1    9         1         1     2
## 133     9       1       1   13         3         1     2
## 134    15       1       1   16         1         1     2
## 135    14       2       1    6        99         1     1
## 136    18       1       1   14         1         1     1
## 137    14       1       1   14         2         1     2
## 138    14       1       1   11         1         1     2
## 139    13       1       1    4        99         1     1
## 140    16       1       1   16         1         1     1
## 141    18       2       1   12         1         1     1
## 142    18       2       1   11         1         1     2
## 143    20       1       1   17         1         1     1
## 144    27       2       1   15         1         1     1
## 145    18       1       1   15         1         1     2
## 146    13       1       1   15         1         1     2
## 147    19       1       2    8         1         1     1
## 148    13       2       1    2        99         1     2
## 149    16       1       1   12         3         1     2
## 150    16       1       1   12         2         1     1
## 151    17       1       1   14         1         1     1
## 152    17       1       1   16         1         1     2
## 153    19       1       1   15         1         1     1
## 154    15       1       1   15         1         1     1
## 155    20       1       1   15         1         1     2
## 156    15       1       1   15         1         1     1
## 157    16       1       1   15         1         1     1
## 158    18       1       1   15         1         1     2
## 159    14       1       1   13         1         1     1
## 160    18       2       1    7         1         1     1
## 161     7       1       1   13         1         1     1
## 162    15       2       1    6        99         1     1
## 163    13       2       1   16         1         1     2
## 164    17       1       1    9         3         1     2
## 165    18       1       1   11         2         1     2
## 166    21       1       1   13         1         1     1
## 167    19       1       1   13         1         1     2
## 168    13       1       1    9         3         1     2
## 169    15       1       1   17         1         1     1
## 170    18       1       1   16         1         1     2
## 171    13       1       1   15         1         1     1
## 172    16       1       1   15         1         1     2
## 173    18       1       1    7         1         1     1
## 174    18       2       1    9         5         1     1
## 175    17       2       1   11         1         1     2
## 176    15       2       1   10         1         1     1
## 177    17       2       1   15         1         1     2
## 178    11       1       1   16         1         1     1
## 179    21       1       1   14         1         1     2
## 180    17       1       1   15         1         3     2
## 181    17       1       1   13         1         1     2
## 182    17       2       1   15         1         1     2
## 183    14       2       1    4        99         1     1
## 184    15       1       1   16         1         1     2
## 185    21       1       1   15         1         1     2
## 186    18       1       1   11         1         1     1
## 187    20       1       1   15         1         1     2
## 188    28       2       1   13         2         1     2
## 189    31       1       1   14         1         1     2
## 190    18       2       1   14         1         1     2
## 191    18       1       1   15         1         1     1
## 192    22       2       2   15         1         1     1
## 193    18       2       1   16         1         1     2
## 194    14       1       1   15         1         1     1
## 195    38       1       1   15         1         1     2
## 196    30       1       1   15         5         1     1
## 197    21       1       1   17         1         1     1
## 198    13       1       1   15         1         1     2
## 199    21       2       1   17         1         1     2
## 200    32       2       1   14         1         1     2
## 201    22       1       1   13         1         1     1
## 202    20       1       1   15         1         1     2
## 203    14       2       1    5        99         1     1
## 204    16       1       1   16         1         1     1
## 205    18       1       1   13         1         1     2
## 206    16       1       1   16         1         1     2
## 207    25       1       1   13         4         1     2
## 208    15       1       1   13         1         1     2
## 209    15       1       1   15         1         1     1
## 210    18       1       1   11         5         1     1
## 211    15       1       1   11         2         1     1
## 212    18       1       1   15         1         1     2
## 213    18       1       1   17         1         1     2
## 214    15       1       1   13         1         1     2
## 215    14       1       1   16         1         1     2
## 216    12       1       1   15         1         1     1
## 217    13       2       2    3        99         1     1
## 218    14       2       1   10         1         1     2
## 219    12       1       1   13         1         1     1
## 220    18       2       1   12         1         1     2
## 221    15       1       1   13         1         1     1
## 222    16       1       1   10         1         1     2
## 223    17       1       1   16         1         1     2
## 224    15       1       2   13         1         2     1
## 225    35       1       1   15         2         1     2
## 226    14       2       2    4        99         1     2
## 227    18       1       1    8         1         1     1
## 228    11       1       1   15         2         1     2
## 229    20       1       1   11         3         2     1
## 230    17       1       1   16         1         1     1
## 231    16       1       1   15         1         1     2
## 232    21       1       1   13         1         1     1
## 233    45       2       1   16         1         1     2
## 234    17       1       1   14         1         1     1
## 235    15       1       1    8         1         1     2
## 236    17       2       1   15         1         1     2
## 237    15       1       1   14         2         1     1
## 238    13       1       1   13         6         1     1
## 239    15       1       1    9         4         1     2
## 240    22       1       1   15         1         1     2
## 241    21       1       1   17         1         1     2
## 242    13       1       1    9         1         1     1
## 243    18       1       1   16         1         1     1
## 244    12       1       1   12         1         1     2
## 245    14       1       1   14         1         1     1
## 246    19       1       1   12         1         1     2
## 247     9       1       1   16         1         1     2
## 248    16       1       1   13         1         1     2
## 249    16       1       1   13         1         1     2
## 250    14       1       1   15         1         2     1
## 251    14       1       1   10         3         1     2
## 252    21       1       1   13         2         1     2
## 253    16       1       1   15         1         1     1
## 254    19       1       1   15         1         1     2
## 255    18       2       1   15         1         1     2
## 256    13       1       1   12         3         1     2
## 257    14       1       1   13         1         1     1
## 258    21       1       1   15         1         1     2
## 259    25       1       1   16         1         1     2
## 260    15       1       2   15         1         1     1
## 261    35       2       1   17         5         1     1
## 262    15       2       1    9         1         1     2
## 263    14       1       1    3        99         1     2
## 264    20       1       1   14         1         1     1
## 265    13       1       1    8         3         1     2
## 266    17       1       1   16         1         1     2
## 267    14       1       1    9         1         1     1
## 268    14       1       1    9         1         1     1
## 269    17       1       1   13         1         1     2
## 270    14       2       1    4        99         1     1
## 271    20       2       1   17         3         1     2
## 272    15       1       1   15         2         1     2
## 273    16       2       1   14         1         1     1
## 274    16       1       1   15         1         1     2
## 275    14       1       1   16         1         1     1
## 276    15       1       1   13         1         1     2
## 277    20       1       1   10         1         1     1
## 278    15       2       1    5        99         1     1
## 279    13       1       1   13         3         2     2
## 280    21       1       1   12         1         1     2
## 281    16       1       1   11         4         1     2
## 282    17       1       1   15         1         2     1
## 283    14       1       1   10         2         1     2
## 284    14       1       1   15         1         1     2
## 285    16       2       1   17         1         1     1
## 286    20       2       1   12         1         1     2
## 287    15       1       1   13         1         1     2
## 288    20       1       1   14         1         1     1
## 289    29       2       1   15         1         1     1
## 290    29       1       1   15         2         1     2
## 291    15       2       1   14         1         1     2
## 292    18       1       1   16         1         1     2
## 293    27       1       1   15         1         1     2
## 294    16       1       1   16         1         1     2
## 295    16       1       1   12         1         1     2
## 296    12       1       1   15         1         2     1
## 297    18       1       1   14         1         2     1
## 298    25       1       1   17         1         2     1
## 299    15       2       1   13         1         1     1
## 300    10       1       1   16         1         1     2
## 301    16       1       1   14         1         1     2
## 302    17       1       1   12         1         2     1
## 303    13       1       1   14         1         1     1
## 304    14       1       1    9         3         1     2
## 305    14       2       1   10         3         1     2
## 306    13       1       1   15         1         1     1
## 307    21       2       1   11         1         1     1
## 308    15       1       1   15         1         1     1
## 309    13       1       1   15         1         1     1
## 310    17       2       1   15         2         1     2
## 311    12       2       1    6        99         2     1
## 312    12       1       1   16         1         1     1
## 313    18       2       1   15         4         3     2
## 314    13       1       1   13         2         1     2
## 315    14       1       1    5        99         1     1
## 316    13       1       1    9         1         1     1
## 317    21       2       1   10         1         1     1
## 318    16       1       1   16         2         1     1
## 319    17       1       1    9         3         1     2
## 320    16       1       1   11         1         1     2
## 321    19       2       1   13         1         1     1
## 322    13       1       1   11         1         1     2
## 323    25       1       1   17         1         1     1
## 324    18       1       1   15         1         1     1
## 325    12       1       1   10         2         1     2
## 326    19       1       1   11         1         1     2
## 327    19       2       1   14         1         1     1
## 328    11       1       1    8         3         1     2
## 329    14       1       1   15         1         1     1
## 330    14       1       1   15         1         2     1
## 331    14       1       1   14         5         1     1
## 332    15       1       1   16         1         1     1
## 333    17       1       1   15         1         1     1
## 334    17       2       2    6        99         1     1
## 335    16       2       1    8         1         1     2
## 336    17       2       1   17         1         1     2
## 337    18       1       1   16         1         1     2
## 338    23       2       1   15         4         2     1
## 339    18       2       1   15         1         1     1
## 340    11       1       1   15         1         1     1
## 341    14       1       1   15         1         1     1
## 342    14       1       1   15         1         1     1
## 343    15       2       1    8         1         1     2
## 344    15       1       1   15         1         1     1
## 345    20       1       1   12         1         1     2
## 346    15       1       1   15         1         1     2
## 347    21       2       1   12         3         1     2
## 348    20       1       2   15         1         1     2
## 349    18       1       1    9         1         1     1
## 350    21       1       1   11         5         1     1
## 351    19       2       1   12         3         1     2
## 352    15       1       1   16         1         1     1
## 353    14       1       1   14         1         1     2
## 354    17       1       1   15         1         1     1
## 355    17       1       1   11         1         1     1
## 356    20       2       1   15         1         3     1
## 357    25       1       1   17         1         1     1
## 358    16       1       1   13         1         1     1
## 359    21       2       1   11         2         1     2
## 360    11       1       1   15         1         1     1
## 361    17       1       1   15         1         1     1
## 362    16       1       1   15         1         1     2
## 363    17       1       1   13         1         4     1
## 364    17       1       1   12         1         1     1
## 365    32       1       1   17         1         1     2
## 366    15       1       1   15         1         1     2
## 367    14       1       1   16         1         1     1
## 368    17       1       1   17         1         1     1
## 369    14       1       1   15         1         1     2
## 370    12       2       1    5        99         1     1
## 371    17       1       1   15         1         1     2
## 372    14       2       1    3        99         1     1
## 373    15       1       1   15         1         1     2
## 374    16       1       1   15         1         1     1
## 375    15       1       1    9         1         1     2
## 376    16       2       1    7         4         1     2
## 377    16       1       1   15         1         1     2
## 378    13       1       1   13         1         1     1
## 379    15       1       1   16         1         1     1
## 380    15       2       1   11         1         1     2
## 381    18       1       1   14         1         1     2
## 382    16       1       1   16         1         1     1
## 383    19       1       1   13         5         1     2
## 384    16       2       1   13         1         1     1
## 385    17       1       1   15         1         1     2
## 386    14       1       1    6        99         1     2
## 387    14       1       1   15         1         1     1
## 388    20       2       1   11         1         1     2
## 389    16       1       1   14         1         1     2
## 390    16       1       1    6        99         1     2
## 391    14       1       1   15         1         1     1
## 392    13       1       1    4        99         2     2
## 393    18       1       1   15         1         1     1
## 394    39       1       1   15         1         1     1
## 395    15       1       1   17         1         1     1
## 396    19       1       1   13         1         1     2
## 397    16       1       1   14         2         1     1
## 398    11       1       1   17         1         1     1
## 399    13       2       1   11         2         1     2
## 400    16       1       1   12         2         1     2
## 401    14       1       1   16         1         1     2
## 402    16       1       1   16         1         1     2
## 403    20       1       1   14         1         2     1
## 404    13       1       1   15         2         1     2
## 405    12       2       2    2        99         1     2
## 406    18       2       1    7         1         1     1
## 407    21       1       1   14         1         1     1
## 408    16       1       1   15         1         1     2
## 409    12       1       1   14         1         1     1
## 410    18       2       1   16         1         1     1
## 411     9       1       1   14         1         1     1
## 412    18       1       1   15         1         1     1
## 413    13       1       1   14         1         1     1
## 414    16       1       1   12         1         1     1
## 415    12       1       1   13         1         1     1
## 416    18       1       1   11         2         1     2
## 417    21       2       1   12         1         1     2
## 418    34       1       1   15         1         1     1
## 419    11       1       1   15         3         1     2
## 420    17       1       1   10         1         1     2
## 421    14       1       1    4        99         1     2
## 422    13       2       1    3        99         1     2
## 423    14       2       1    8         4         1     2
## 424    20       1       1   13         3         1     2
## 425    15       1       1   13        97        97     2
## 426    16       2       1    9         1         1     2</code></pre>
<pre class="r"><code>dat2 &lt;- read.csv(file = &quot;dat.nsduh.small.csv&quot;)</code></pre>
<p>What are the dimensions of the dataset?</p>
<pre class="r"><code>names(dat2)</code></pre>
<pre><code>## [1] &quot;mjage&quot;     &quot;cigever&quot;   &quot;alcever&quot;   &quot;AGE2&quot;      &quot;sexatract&quot; &quot;speakengl&quot;
## [7] &quot;irsex&quot;</code></pre>
<p>The variables are mjaje, cigever, alcever, age2, sexatract, speakenglish, irsex.</p>
</div>
<div id="problem-2-variables" class="section level1">
<h1>Problem 2: Variables</h1>
<p>Describe the variables in the data set.</p>
<pre class="r"><code>summary(dat2)</code></pre>
<pre><code>##      mjage          cigever         alcever           AGE2      
##  Min.   : 7.00   Min.   :1.000   Min.   :1.000   Min.   : 1.00  
##  1st Qu.:14.00   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:11.00  
##  Median :16.00   Median :1.000   Median :1.000   Median :14.00  
##  Mean   :17.08   Mean   :1.256   Mean   :1.028   Mean   :12.77  
##  3rd Qu.:18.00   3rd Qu.:2.000   3rd Qu.:1.000   3rd Qu.:15.00  
##  Max.   :45.00   Max.   :2.000   Max.   :2.000   Max.   :17.00  
##    sexatract       speakengl          irsex      
##  Min.   : 1.00   Min.   : 1.000   Min.   :1.000  
##  1st Qu.: 1.00   1st Qu.: 1.000   1st Qu.:1.000  
##  Median : 1.00   Median : 1.000   Median :2.000  
##  Mean   :10.09   Mean   : 1.758   Mean   :1.507  
##  3rd Qu.: 2.00   3rd Qu.: 1.000   3rd Qu.:2.000  
##  Max.   :99.00   Max.   :98.000   Max.   :2.000</code></pre>
<p>All of the variables in our study have been made into quantitative variables. For each of the questions, the response was a numerical answer. Even for the questions that could have been seen as categorical, the respondents answered with a number. The responses to each question were coded into a numerical value.For example, one of the variables is sexual attraction, and the responses are “I am only attracted to the opposite sex”, “I am mostly attracted to opposite sex”, “I am equally attracted to males and females”, “I am mostly attracted to the same sex”, “I am only attracted to the same sex”, and “I am not sure” all correspond to a numerical value. This is useful because we are able to use quantitative variable techniques to learn more about the sample. For example, we can calculate the mean and median because our responses have been translated into numbers.</p>
</div>
<div id="what-is-this-data-set-about-who-collected-the-data-what-kind-of-sample-is-it-and-what-was-the-purpose-of-generating-the-data" class="section level1">
<h1>What is this data set about? Who collected the data, what kind of sample is it, and what was the purpose of generating the data?</h1>
<p>This data set is just a small sample taken from the 2019 National Survey of Drug Use and Health. The National Survey on Drug Use and Health (NSDUH) was collected by the US Department of Health and Human Services. NSDUH is a sample survey of the population of United States citizens aged 12 and older. The goal of this survey is to generate a large statistical information data base on the use of alcohol, tobacco, drugs, and mental health in the United States. The survey wants to track trends in substance use and mental illness. For the purpose of this class, we only are looking at some of the data collected in this survey. We are focused on looking at the trends and spread of the data collected about the age of first marijuana use, the age when individuals first started smoking cigarettes everyday, and the age of first alcohol use. We also are looking at the data that asks how well the respondent speaks English, their current age, their sexual attraction, and their gender.</p>
<p>#Problem 3: Age and gender</p>
<p>What is the age distribution of the sample like? Make sure you read the codebook to know what the variable values mean.</p>
<p>The histogram does not directly express the years of age along the x axis. The ages of the respondents were coded into groups. For example, a value of 1 for age corresponds to the responded being 12 years old I feel that it is difficult to really determine the distribution of ages, because some numerical values correspond to only a single year of age and others correspond to larger age groups, such as 50-64 year olds. I think it would be better if the ages were expressed as a normal quantitative data set, or each numerical value corresponded to age groups of the same length (for example, the age range for each was 3 years for all, and not varying).From summarizing the data for AGE2 and producing a histogram, I can see that the average was 13.98 which corresponds to an average respondent age of between 30 and 34 years of age. Respondents were all over the age of 12. The histogram allows for the visualization of the spread. The data appears to be skewed left, but I think that this could just be a result of how the ages were grouped. Of course the graph would appear to be skewed left when the second half of the age code encompasses ages 22 through 65+.</p>
</div>
<div id="do-you-think-this-age-distribution-representative-of-the-us-population-why-or-why-not" class="section level1">
<h1>Do you think this age distribution representative of the US population? Why or why not?</h1>
<p>No, I do not think that this age distribution is representative of the US population because there is no representation of the population under 12 years of age. Although these questions would not be appropriate to ask children, if the sampling was for all ages, then perhaps the age distribution would be representative of the US population. Also, it would make more sense that there would more people under 25 because not all children reach adulthood.</p>
</div>
<div id="is-the-sample-balanced-in-terms-of-gender-if-not-are-there-more-females-or-males" class="section level1">
<h1>Is the sample balanced in terms of gender? If not, are there more females or males?</h1>
<pre class="r"><code>counts &lt;- table(dat2$irsex)
barplot(counts, main=&quot;Gender Distribution&quot;, xlab=&quot;Gender&quot;, ylab=&quot;Frequency&quot;, names=c(&quot;Male&quot;, &quot;Female&quot;), ylim=c(0,300), col=&quot;sky blue&quot;)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre class="r"><code>counts &lt;- table(dat2$irsex)</code></pre>
<pre class="r"><code>pie(counts, labels=c(&quot;Male&quot;, &quot;Female&quot;), main=&quot;Gender Distribution&quot;)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code>table(dat2$irsex)</code></pre>
<pre><code>## 
##   1   2 
## 210 216</code></pre>
<p>I used both a bar plot and pie chart to look at the gender distribution. From both graphs, I can see that the sample is not 50% men, 50% women. There are more male responses in our sample than women. However, the difference is only slight. If there was an equal number of men (1) and women (2) in this study, the mean would be exactly 1.5. However, the mean is slightly less than 1.5, it is 1.468. Because the mean is pulled slightly closer to 1 (which is the numerical code for male respondent).Also, I was able to make a table of irsex and see how many respondents answered 1(male) or 2(female), 91 answered male and 80 answered female.</p>
</div>
<div id="use-this-code-to-draw-a-stacked-bar-plot-to-view-the-relationship-between-sex-and-age.-what-can-you-conclude-from-this-plot" class="section level1">
<h1>Use this code to draw a stacked bar plot to view the relationship between sex and age. What can you conclude from this plot?</h1>
<p>From a stacked bar plot, we can compare the age and sex distributions of the respondents simultaneously. With this bar plot, we can compare how sex is distributed in each age category. For example, in age category 8, which corresponds to respondent is 19 years old, we can see that there were much more female respondents than male (if there were any male at all).</p>
<div id="problem-4-substance-use" class="section level2">
<h2>Problem 4: Substance use</h2>
</div>
</div>
<div id="for-which-of-the-three-substances-included-in-the-data-set-marijuana-alcohol-and-cigarettes-do-individuals-tend-to-use-the-substance-earlier" class="section level1">
<h1>For which of the three substances included in the data set (marijuana, alcohol, and cigarettes) do individuals tend to use the substance earlier?</h1>
<pre class="r"><code>summary(dat2)</code></pre>
<pre><code>##      mjage          cigever         alcever           AGE2      
##  Min.   : 7.00   Min.   :1.000   Min.   :1.000   Min.   : 1.00  
##  1st Qu.:14.00   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:11.00  
##  Median :16.00   Median :1.000   Median :1.000   Median :14.00  
##  Mean   :17.08   Mean   :1.256   Mean   :1.028   Mean   :12.77  
##  3rd Qu.:18.00   3rd Qu.:2.000   3rd Qu.:1.000   3rd Qu.:15.00  
##  Max.   :45.00   Max.   :2.000   Max.   :2.000   Max.   :17.00  
##    sexatract       speakengl          irsex      
##  Min.   : 1.00   Min.   : 1.000   Min.   :1.000  
##  1st Qu.: 1.00   1st Qu.: 1.000   1st Qu.:1.000  
##  Median : 1.00   Median : 1.000   Median :2.000  
##  Mean   :10.09   Mean   : 1.758   Mean   :1.507  
##  3rd Qu.: 2.00   3rd Qu.: 1.000   3rd Qu.:2.000  
##  Max.   :99.00   Max.   :98.000   Max.   :2.000</code></pre>
<p>To answer this question, I looked at both the minimum age and the average age for the first time trying each of these substances. The youngest that any of these respondents had ever tried alcohol was 5 years old, whereas the youngest that anyone had ever tried cigarettes or marijuana was 10 and 7, respectively.The average age at first alcohol drink was 14.95 or ~15 years old. The average age at first cigarette was 17.65 years old and the average age of first time using marijuana was 15.99 or ~16. On average, individuals tend to use alcohol earliest.</p>
<div id="problem-5-sexual-attraction" class="section level2">
<h2>Problem 5: Sexual attraction</h2>
</div>
</div>
<div id="what-does-the-distribution-of-sexual-attraction-look-like-is-this-what-you-expected" class="section level1">
<h1>What does the distribution of sexual attraction look like? Is this what you expected?</h1>
<pre class="r"><code>counts &lt;- table(dat2$sexatract)
barplot(counts, ylim = c(0,150), main=&quot;Sexual Attraction/Orientation Distribution&quot;, xlab=&quot;Sexual Attraction&quot;, names=c(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;, &quot; 5&quot;, &quot;6&quot;, &quot;97&quot;, &quot;98&quot;,&quot;99&quot;))</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-20-1.png" width="672" /> The majority of respondents are straight/only attracted to the opposite sex. For this variable, it is not helpful to look at the mean, because it is skewed due to the code 99 for skipped question. By looking at both the bar plot and the median, Q1 and Q3, I can see that almost all of the data falls in the opposite sex only code of 1. This is not what I expected at all.Especially today, in which there is a greater level of acceptance of LGBTQIA+ individuals, I would feel that the distribution would not be so centered around 1, only opposite sex attraction.</p>
</div>
<div id="what-is-the-distribution-of-sexual-attraction-by-gender" class="section level1">
<h1>What is the distribution of sexual attraction by gender?</h1>
<pre class="r"><code>tab.gendersexattract &lt;- table(dat2$irsex, dat2$sexatract)
barplot(tab.gendersexattract,
        main = &quot;Sexual Attraction of Men and Women&quot;, ylim=c(0,150), 
        xlab = &quot;Sexual Attraction&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.gendersexattract),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<div id="problem-6-english-speaking" class="section level2">
<h2>Problem 6: English speaking</h2>
</div>
</div>
<div id="what-does-the-distribution-of-english-speaking-look-like-in-the-sample-is-this-what-you-might-expect-for-a-random-sample-of-the-us-population" class="section level1">
<h1>What does the distribution of English speaking look like in the sample? Is this what you might expect for a random sample of the US population?</h1>
<pre class="r"><code>counts &lt;- table(dat2$speakengl)
barplot(counts, ylim = c(0,200), main=&quot;English Speaking Ability&quot;, xlab=&quot;Language Code &quot;)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-22-1.png" width="672" /> To answer this question, I looked at both the median, mean, Q1, Q3, and a bar chart for the data collected on English speaking ability.75% or more of the respondents can speak English very well, looking at Q3.</p>
<pre class="r"><code>table(dat2$speakengl)</code></pre>
<pre><code>## 
##   1   2   3   4  97  98 
## 396  21   5   1   2   1</code></pre>
<p>Also, by making a table with the data from speakengl, I am able to see that 161 of the respondents answered that they speak English very well, in comparison to only 8 answering 2(well) and 2 answering 3(not well).</p>
</div>
<div id="are-there-more-english-speaker-females-or-males" class="section level1">
<h1>Are there more English speaker females or males?</h1>
<pre class="r"><code>tab.genderspeakengl &lt;- table(dat2$irsex, dat2$speakengl)
barplot(tab.genderspeakengl,
        main = &quot;English Speaking Ability of Men and Women&quot;, ylim=c(0,200), 
        xlab = &quot;English Speaking Ability&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.genderspeakengl),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre class="r"><code>table(dat2$speakengl, dat2$irsex)</code></pre>
<pre><code>##     
##        1   2
##   1  192 204
##   2   15   6
##   3    1   4
##   4    1   0
##   97   0   2
##   98   1   0</code></pre>
<p>Looking at the stacked bar plot for gender and English speaking ability, I can’t really tell if there are more men or more women able to speak English.I decided to make a table to see exactly how many men and women answered 1 (speaks English very well). From this table, I can see that 84 men answered this, whereas only 77 women answered that they can speak English very well.However, there were more male respondents than female, so I decided to calculate percent of men and percent of women can speak English “very well”. 96.25% of female respondents speak English very well. 86.6% of male respondents speak English very well. A greater percent of female respondents are able to speak English very well. However, just looking at number of respondents, more men speak English very well.</p>
<p><span class="math display">\[\\[2in]\]</span></p>
</div>
<div id="instructions" class="section level1">
<h1>Instructions</h1>
<ol style="list-style-type: lower-alpha">
<li><p>Create a folder in your computer (a good place would be under Crim 250, Exams).</p></li>
<li><p>Download the dataset from the Canvas website (fatal-police-shootings-data.csv) onto that folder, and save your Exam 1.Rmd file in the same folder.</p></li>
<li><p>Download the README.md file. This is the codebook.</p></li>
<li><p>Load the data into an R data frame.</p></li>
</ol>
<pre class="r"><code>datexam &lt;- read.csv(&quot;fatal-police-shootings-data.csv&quot;)</code></pre>
</div>
<div id="problem-1-10-points" class="section level1">
<h1>Problem 1 (10 points)</h1>
<ol style="list-style-type: lower-alpha">
<li>Describe the dataset. This is the source: <a href="https://github.com/washingtonpost/data-police-shootings" class="uri">https://github.com/washingtonpost/data-police-shootings</a> . Write two sentences (max.) about this.</li>
</ol>
<p><strong>This data set is a record of every fatal police shooting in the United States since January 1, 2015. The data set gives a unique identification for each victim, the name of the victim, the date of the shooting, the manner of death, whether the victim was armed, the age, gender, and race of the victim, the city and state of the shooting, whether or not the victim had signs of mental illness, the threat level, how/if the victim tried to flee, whether or not a body camera was worn by the officer, the latitude and longitude location, and the accuracy of these coordinates. </strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>How many observations are there in the data frame?</li>
</ol>
<pre class="r"><code>names(datexam)</code></pre>
<pre><code>##  [1] &quot;id&quot;                      &quot;name&quot;                   
##  [3] &quot;date&quot;                    &quot;manner_of_death&quot;        
##  [5] &quot;armed&quot;                   &quot;age&quot;                    
##  [7] &quot;gender&quot;                  &quot;race&quot;                   
##  [9] &quot;city&quot;                    &quot;state&quot;                  
## [11] &quot;signs_of_mental_illness&quot; &quot;threat_level&quot;           
## [13] &quot;flee&quot;                    &quot;body_camera&quot;            
## [15] &quot;longitude&quot;               &quot;latitude&quot;               
## [17] &quot;is_geocoding_exact&quot;</code></pre>
<p><strong>There are 17 different variables in the data frame. 6954 individuals were observed (6954 victims). </strong></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Look at the names of the variables in the data frame. Describe what “body_camera”, “flee”, and “armed” represent, according to the codebook. Again, only write one sentence (max) per variable.</li>
</ol>
<pre class="r"><code>summary(datexam)</code></pre>
<pre><code>##        id           name               date           manner_of_death   
##  Min.   :   3   Length:6594        Length:6594        Length:6594       
##  1st Qu.:1860   Class :character   Class :character   Class :character  
##  Median :3662   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :3651                                                           
##  3rd Qu.:5437                                                           
##  Max.   :7194                                                           
##                                                                         
##     armed                age           gender              race          
##  Length:6594        Min.   : 6.00   Length:6594        Length:6594       
##  Class :character   1st Qu.:27.00   Class :character   Class :character  
##  Mode  :character   Median :35.00   Mode  :character   Mode  :character  
##                     Mean   :37.12                                        
##                     3rd Qu.:45.00                                        
##                     Max.   :91.00                                        
##                     NA&#39;s   :308                                          
##      city              state           signs_of_mental_illness
##  Length:6594        Length:6594        Length:6594            
##  Class :character   Class :character   Class :character       
##  Mode  :character   Mode  :character   Mode  :character       
##                                                               
##                                                               
##                                                               
##                                                               
##  threat_level           flee           body_camera          longitude      
##  Length:6594        Length:6594        Length:6594        Min.   :-160.01  
##  Class :character   Class :character   Class :character   1st Qu.:-112.09  
##  Mode  :character   Mode  :character   Mode  :character   Median : -94.31  
##                                                           Mean   : -97.16  
##                                                           3rd Qu.: -83.12  
##                                                           Max.   : -67.87  
##                                                           NA&#39;s   :314      
##     latitude     is_geocoding_exact
##  Min.   :19.50   Length:6594       
##  1st Qu.:33.48   Class :character  
##  Median :36.09   Mode  :character  
##  Mean   :36.66                     
##  3rd Qu.:40.00                     
##  Max.   :71.30                     
##  NA&#39;s   :314</code></pre>
<p><strong>“body_camera” is a categorical variable that represents whether or not the officer was reported in the news to be wearing a body cam at the time of the incident and whether or not any of the incident was recorded. “flee” is another categorical variable that represents whether or not news reports indicated that the victim was fleeing at the time of shooting and if it was by foot or car. “armed” is another categorical variable that indicates if the victim was armed. </strong></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What are three weapons that you are surprised to find in the “armed” variable? Make a table of the values in “armed” to see the options.</li>
</ol>
<pre class="r"><code>table(datexam$armed)</code></pre>
<pre><code>## 
##                                                   air conditioner 
##                              207                                1 
##                       air pistol                   Airsoft pistol 
##                                1                                3 
##                               ax                         barstool 
##                               24                                1 
##                     baseball bat          baseball bat and bottle 
##                               20                                1 
## baseball bat and fireplace poker           baseball bat and knife 
##                                1                                1 
##                            baton                           BB gun 
##                                6                               15 
##               BB gun and vehicle                     bean-bag gun 
##                                1                                1 
##                      beer bottle                       binoculars 
##                                3                                1 
##                     blunt object                           bottle 
##                                5                                1 
##                    bow and arrow                       box cutter 
##                                1                               13 
##                            brick              car, knife and mace 
##                                2                                1 
##                          carjack                            chain 
##                                1                                3 
##                        chain saw                         chainsaw 
##                                2                                1 
##                            chair              claimed to be armed 
##                                4                                1 
##               contractor&#39;s level                   cordless drill 
##                                1                                1 
##                         crossbow                          crowbar 
##                                9                                5 
##                        fireworks                         flagpole 
##                                1                                1 
##                       flashlight                      garden tool 
##                                2                                2 
##                      glass shard                          grenade 
##                                4                                1 
##                              gun                      gun and car 
##                             3798                               12 
##                    gun and knife                  gun and machete 
##                               22                                3 
##                    gun and sword                  gun and vehicle 
##                                1                               17 
##              guns and explosives                           hammer 
##                                3                               18 
##                       hand torch                          hatchet 
##                                1                               14 
##                  hatchet and gun                         ice pick 
##                                2                                1 
##                incendiary device                            knife 
##                                2                              955 
##                knife and vehicle                 lawn mower blade 
##                                1                                2 
##                          machete                  machete and gun 
##                               51                                1 
##                     meat cleaver                  metal hand tool 
##                                6                                2 
##                     metal object                       metal pipe 
##                                5                               16 
##                       metal pole                       metal rake 
##                                4                                1 
##                      metal stick                       microphone 
##                                3                                1 
##                       motorcycle                         nail gun 
##                                1                                1 
##                              oar                       pellet gun 
##                                1                                3 
##                              pen                     pepper spray 
##                                1                                2 
##                         pick-axe                    piece of wood 
##                                4                                7 
##                             pipe                        pitchfork 
##                                7                                2 
##                             pole                   pole and knife 
##                                3                                2 
##                  railroad spikes                             rock 
##                                1                                7 
##                    samurai sword                         scissors 
##                                4                                9 
##                      screwdriver                     sharp object 
##                               16                               14 
##                           shovel                            spear 
##                                7                                2 
##                          stapler              straight edge razor 
##                                1                                5 
##                            sword                            Taser 
##                               23                               34 
##                        tire iron                       toy weapon 
##                                4                              226 
##                          unarmed                     undetermined 
##                              421                              188 
##                   unknown weapon                          vehicle 
##                               82                              213 
##                  vehicle and gun              vehicle and machete 
##                                8                                1 
##                    walking stick                       wasp spray 
##                                1                                1 
##                           wrench 
##                                1</code></pre>
<p><strong>This is a very extensive and interesting list of weapons that the victims were armed with. Three weapons that I was surprised to find in the armed variable were: air conditioner, railroad spikes, and flashlight. Another weapon that was shocking was a “toy weapon”. </strong></p>
</div>
<div id="problem-2-10-points" class="section level1">
<h1>Problem 2 (10 points)</h1>
<ol style="list-style-type: lower-alpha">
<li>Describe the age distribution of the sample. Is this what you would expect to see?</li>
</ol>
<pre class="r"><code>hist(datexam$age, main=&quot;Distribution of Age of Police Shoooting Victims&quot;, xlab=&quot;Age&quot;, ylab=&quot;Frequency&quot;, xlim=c(0,100 ), ylim=c(0,1500),col=&quot;yellow&quot;, breaks=25)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p><strong>The distribution of the data is skewed fairly right. According to the data, the youngest victim was 6 years old and the oldest victim was 91 years old. This is a very wide spread and I was shocked and upset to see that the youngest victim of police shooting was 6 years old. 50% of the victims were between the ages of 27 and 45, according to Q1 and Q3. The distribution is skewed fairly right, with a concentration of victims between the ages of 27 to 45. The average age of victims was 37.12 years old. The median was 35 for this data set. </strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>To understand the center of the age distribution, would you use a mean or a median, and why? Find the one you picked.</li>
</ol>
<pre class="r"><code>summary(datexam)</code></pre>
<pre><code>##        id           name               date           manner_of_death   
##  Min.   :   3   Length:6594        Length:6594        Length:6594       
##  1st Qu.:1860   Class :character   Class :character   Class :character  
##  Median :3662   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :3651                                                           
##  3rd Qu.:5437                                                           
##  Max.   :7194                                                           
##                                                                         
##     armed                age           gender              race          
##  Length:6594        Min.   : 6.00   Length:6594        Length:6594       
##  Class :character   1st Qu.:27.00   Class :character   Class :character  
##  Mode  :character   Median :35.00   Mode  :character   Mode  :character  
##                     Mean   :37.12                                        
##                     3rd Qu.:45.00                                        
##                     Max.   :91.00                                        
##                     NA&#39;s   :308                                          
##      city              state           signs_of_mental_illness
##  Length:6594        Length:6594        Length:6594            
##  Class :character   Class :character   Class :character       
##  Mode  :character   Mode  :character   Mode  :character       
##                                                               
##                                                               
##                                                               
##                                                               
##  threat_level           flee           body_camera          longitude      
##  Length:6594        Length:6594        Length:6594        Min.   :-160.01  
##  Class :character   Class :character   Class :character   1st Qu.:-112.09  
##  Mode  :character   Mode  :character   Mode  :character   Median : -94.31  
##                                                           Mean   : -97.16  
##                                                           3rd Qu.: -83.12  
##                                                           Max.   : -67.87  
##                                                           NA&#39;s   :314      
##     latitude     is_geocoding_exact
##  Min.   :19.50   Length:6594       
##  1st Qu.:33.48   Class :character  
##  Median :36.09   Mode  :character  
##  Mean   :36.66                     
##  3rd Qu.:40.00                     
##  Max.   :71.30                     
##  NA&#39;s   :314</code></pre>
<p><strong>To describe the center of the age distribution, I used the median age. The median age gives a better description of the center of the age distribution because it is the point where half of the victims are younger than and half of the victims are older than this age. Mean is the average age of the people but median gives a better description of the true center of the distribution.</strong></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Describe the gender distribution of the sample. Do you find this surprising?</li>
</ol>
<pre class="r"><code>table(datexam$gender)</code></pre>
<pre><code>## 
##         F    M 
##    3  293 6298</code></pre>
<pre class="r"><code>counts &lt;- table(datexam$gender)
barplot(counts, main=&quot;Gender Distribution of Police Shooting Victims&quot;, xlab=&quot;Gender&quot;, ylab=&quot;Frequency&quot;, names=c(&quot;unknown&quot;, &quot;Female&quot;,&quot;Male&quot;),ylim=c(0,7000), col=&quot;sky blue&quot;, legend=TRUE)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p><strong>Because gender is a categorical variable, I used a bar plot to look at the distribution of the same. There are three categories for gender: female, male, and unknown gender. Looking at the table displaying the counts of male and female victims in union with the bar plot, it is clear that the number of male police shooting victims outweighs the number of female police shooting victims. I am not surprised by this, especially with the recent news and all of the reports I have heard about about male shooting victims. 3 victims had unknown gender, 293 were women, and 6298 were men. </strong></p>
</div>
<div id="problem-3-10-points" class="section level1">
<h1>Problem 3 (10 points)</h1>
<ol style="list-style-type: lower-alpha">
<li>How many police officers had a body camera, according to news reports? What proportion is this of all the incidents in the data? Are you surprised that it is so high or low?</li>
</ol>
<pre class="r"><code>table(datexam$body_camera)</code></pre>
<pre><code>## 
## False  True 
##  5684   910</code></pre>
<p><strong>910 police officers had a body camera. 13.8% of police officers were wearing a body camera and could have recorded a portion of the incidents I am surprised that this is so low. You would think that if a police officer was being attacked they would activate their body camera to record the incident. However, with all of the recent news about the various police shooting incidents, I am not surprised that police officers are not using their body cameras in incidents were the victims were not actually a threat. </strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>In how many of the incidents was the victim fleeing? What proportion is this of the total number of incidents in the data? Is this what you would expect?</li>
</ol>
<pre class="r"><code>table(datexam$flee)</code></pre>
<pre><code>## 
##                     Car        Foot Not fleeing       Other 
##         491        1058         845        3952         248</code></pre>
<p><strong>In 1058 incidents, the victim was feeling by car. In 845 incidents, they were fleeing by foot. In 491, it is unknown whether or not the victim was fleeing. In total, in 1903 of these incidents, the victim was fleeing before being shot. In 16.58% of the incidents, the victim was fleeing before the shooting. I honestly cannot decide whether or not this is what I would expect. </strong></p>
</div>
<div id="problem-4-10-points---answer-only-one-of-these-a-or-b." class="section level1">
<h1>Problem 4 (10 points) - Answer only one of these (a or b).</h1>
<ol style="list-style-type: lower-alpha">
<li>Describe the relationship between the variables “body camera” and “flee” using a stacked barplot. What can you conclude from this relationship?</li>
</ol>
<p><em>Hint 1: The categories along the x-axis are the options for “flee”, each bar contains information about whether the police officer had a body camera (vertically), and the height along the y-axis shows the frequency of that category).</em></p>
<p><em>Hint 2: Also, if you are unsure about the syntax for barplot, run ?barplot in R and see some examples at the bottom of the documentation. This is usually a good way to look up the syntax of R code. You can also Google it.</em></p>
<p><strong>Your answer here.</strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Describe the relationship between age and race by using a boxplot. What can you conclude from this relationship?</li>
</ol>
<p><em>Hint 1: The categories along the x-axis are the race categories and the height along the y-axis is age.</em></p>
<p><em>Hint 2: Also, if you are unsure about the syntax for boxplot, run ?boxplot in R and see some examples at the bottom of the documentation. This is usually a good way to look up the syntax of R code. You can also Google it.</em></p>
<pre class="r"><code>table(datexam$race)</code></pre>
<pre><code>## 
##         A    B    H    N    O    W 
##  752  106 1553 1083   91   47 2962</code></pre>
<pre class="r"><code>plot(factor(datexam$race), datexam$age, ylab=&quot;Age&quot;, xlab=&quot;Race&quot;, names=c(&quot;unknown&quot;, &quot;Asian&quot;, &quot;Black&quot;, &quot;Hispanic&quot;, &quot;NA&quot;, &quot;Other&quot;, &quot;White&quot;), main=&quot;Relationship between Age and Race of Police Shooting Victims&quot;, col=&quot;red&quot;)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<pre class="r"><code>table(datexam$age, datexam$race)</code></pre>
<pre><code>##     
##            A   B   H   N   O   W
##   6    0   0   0   0   0   0   2
##   12   0   0   0   0   0   0   1
##   13   0   0   1   1   0   0   0
##   14   0   0   0   2   1   0   0
##   15   1   1   6   5   0   0   3
##   16   3   3  11   8   0   0  10
##   17   0   0  24  12   0   0  20
##   18   2   3  50  25   1   3  25
##   19   2   2  45  18   3   0  28
##   20   4   2  41  19   2   2  35
##   21   6   2  54  31   2   0  29
##   22  11   2  45  38   1   2  39
##   23   9   1  56  27   2   1  52
##   24   7   0  69  34   5   1  63
##   25  11   3  76  37   5   3  81
##   26  14   4  39  40   3   1  87
##   27  17   3  69  44   8   4  72
##   28  13   4  59  44   4   1  69
##   29  14   1  57  41   3   4  84
##   30  20   2  52  32   4   4  90
##   31  22   2  69  33   2   1  94
##   32  16   4  53  34   6   1  93
##   33  14   4  53  38   3   1  92
##   34  13   4  44  41   4   2 101
##   35  19   7  43  39   4   0  84
##   36  12   3  34  34   4   2  97
##   37  11   2  51  45   2   0  72
##   38  13   5  31  39   1   2  73
##   39  16   2  46  29   2   0  70
##   40  17   1  24  23   1   1  73
##   41  10   2  32  23   1   1  73
##   42  10   2  19  19   1   1  60
##   43  13   1  22  12   4   0  68
##   44   8   3  14  18   2   0  56
##   45  10   3  19  20   1   1  72
##   46  14   1  19  18   1   1  55
##   47   9   2  25  16   0   0  63
##   48  16   2  20   9   0   2  61
##   49  15   2  17  10   2   0  57
##   50   7   2  11  16   1   0  58
##   51   7   1  10   9   1   1  60
##   52  12   2  12  13   0   0  43
##   53  12   3   9   3   1   0  50
##   54  14   1   8   3   1   1  43
##   55   9   2  12  10   0   0  34
##   56   8   1   6   3   0   1  53
##   57   5   0  11   7   0   0  35
##   58   2   0   3   5   1   0  45
##   59  12   1   2   4   0   1  46
##   60   4   3   7   2   0   0  31
##   61   5   1  10   1   0   0  27
##   62   7   1   5   3   0   0  29
##   63   8   0   6   2   0   0  19
##   64   5   0   2   1   0   0  17
##   65   7   0   2   3   0   0  16
##   66   2   0   2   1   0   0  14
##   67   4   0   5   0   0   0  14
##   68   2   0   5   0   0   0   9
##   69   2   0   1   3   0   0  11
##   70   3   0   1   3   0   0   9
##   71   3   0   0   2   0   0   7
##   72   2   0   1   0   0   0   4
##   73   3   0   0   1   0   0   3
##   74   1   0   2   0   0   0   3
##   75   1   0   0   0   0   0   4
##   76   3   0   0   0   0   0   9
##   77   2   0   1   0   0   0   2
##   78   0   0   0   0   0   0   1
##   79   0   0   0   0   0   0   4
##   80   3   0   0   1   0   0   1
##   81   1   0   0   0   0   0   2
##   82   0   0   0   0   0   0   2
##   83   1   0   0   0   0   0   2
##   84   0   0   0   0   0   0   4
##   86   2   0   0   0   0   0   0
##   88   0   0   1   0   0   0   0
##   89   1   0   0   0   0   0   0
##   91   0   0   0   0   0   0   2</code></pre>
<p><strong>NA stands for Native American on our box plot. The box for “unknown” is missing or unknown racial data. We should ignore this in our analysis of age distribution within race. The box plot shows the distribution of age within each race category. This box plot breaks the victims into their race categories, and then displays the distribution of age in each category. From the box plot, we visualize the distribution of age in each race more easily and compare the distributions across races. From this, I can see that the ages of white victims of police shootings has the most spread. From looking at the table, I can see that the minimum age of white victims was 6 years old and the maximum age was 91. The range for the other racial categories is not as large. Looking at the box plots for all of the relationships, I can see that the average age of police shooting victims of for all 6 racial categories is under 40. There are a few age outliers for each race, the most for Black. The whiskers on the “white” boxplot are much longer than others. From this boxplot, we can conclude that, regardless of outliers and other discrepancies, the distribution of age of police shooting victims is similar regardless of victim’s race. </strong></p>
</div>
<div id="extra-credit-10-points" class="section level1">
<h1>Extra credit (10 points)</h1>
<ol style="list-style-type: lower-alpha">
<li>What does this code tell us?</li>
</ol>
<pre class="r"><code>mydates &lt;- as.Date(dat$date)
head(mydates)
(mydates[length(mydates)] - mydates[1])</code></pre>
<p><strong>The first line is loading the data as calendar dates (d/m/year). I am not sure about the rest of the code. </strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>On Friday, a new report was published that was described as follows by The Guardian: “More than half of US police killings are mislabelled or not reported, study finds.” Without reading this article now (due to limited time), why do you think police killings might be mislabelled or underreported? <strong>The recent frequency of police shootings has produced strong negative feelings towards police officers and law enforcement. With the increase of participation in the “black lives matter” movement (which is extremely important), police officers are under attack for police killings. I feel that this could definitely be the reason for mislabeling and under-reporting of police killings. In order to prevent backlash from both inside the specific community and outside community, police killings are being mislabeled and underreported. I find this extremely concerning, espcially if this is the reasoning. Police officers need to be held accountable for their decisions, especially when their decisions lead to the slaying of innocent individuals.</strong></p></li>
<li><p>Regarding missing values in problem 4, do you see any? If so, do you think that’s all that’s missing from the data? <strong>In problem 4, I see that there is a category for race that is “unknown”. This variable is different from “other” because the race was either not reported or unknown by the data collectors. I also saw in gender and weapon that there was a category for “unknown” where data was missing or unreported. Therefore, I do think that there is data that is missing from throughout the data set, not just in race.</strong></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
